# Globals

# Site Name
EVENTS_SITE_NAME = "[BETA]"

# Error codes
EVENTS_SUCCESS = 0
EVENTS_ERROR = -1
EVENTS_USER_NOT_FOUND = -2
EVENTS_WRONG_ACTIVATION_KEY = -3

# User roles
USER_ROLE_ADMIN = 0
USER_ROLE_MODERATOR = 1
USER_ROLE_USER = 2
USER_ROLE_DEACTIVATED = 3
USER_ROLE_BANNED = 4
USER_ROLE_GUEST = 5

# Site Settings
DOCUMENT_ROOT = "/media/"

# Activation
SENDER_EMAIL = "no-reply@%s.fon-tech.com"

# Sessions
SESSION_COOKIE_NAME = 'session_data'
